### ISSUE TITLE
Small BOM itemm issues

### ISSUE THREAD

**Issue by JWalkinhood** [blueseerERP/blueseer#27]
If I make a change to the price in the item master after bom creation the price does not carry through even if I remove the original line for that part and add again. Also if I try to re-enter the item master after making a change and reviewing the bom it crashes the software.

Love what you are doing, keep up the good work!

**Comment by vaughnte** [comment]
I believe the problem is with standard versus current cost.   If you have a component that you have added to a parent item BOM, you will see the component 'standard' cost in the lower left corner (table) of the BOM menu.   If you change that component price in the item master, you will need to roll the 'standard' of that component before the new cost is reflected.   If you look at the Cost/BOM tab in the item master of the component, you will see a current cost and standard cost...these are probably different in the case you describe.   Type 'roll' in the navcode box, and choose the component and click the roll button.   Then go back to the BOMM menu, and you will see that the 'standard' cost of the item has changed.   You will then need to roll the parent item to absorb this new standard cost rollup...(just click roll in the BOMM menu).   With regards to the crash (I assume by deleting the component in the item master and returning to the BOMM parent), I am unable to reproduce that effect.   Send the app.log file in blueseer/data directory to support@blueseer.com.   Maybe the crash is noted there.   Also, let me know what patch you're on...6.0.x .

**Comment by vaughnte** [comment]
Note....the BOM will always require 'standard' cost of parent and all components....but in hindsight....it may be beneficial to add 'current' cost in the table in the BOMM Maintenance.   I'll look into doing this.   It should not require a schema change...and therefore I can probably include it in the next patch.

**Comment by JWalkinhood** [comment]
Your understanding above is correct. I failed to do the roll up after making the change. Once the roll was completed the cost carried through as described. I apologize as this appears to be operator error vs a bug. 
I regards to the system hang, after rolling the costs I am unable to re produce this myself. When I get home I will send the app.log file as requested. Patch 6.0.7

**Comment by vaughnte** [comment]
On another note...during my research on this I discovered a bug in the BOMM menu with regards to the total sum in the 'material' field.   If 2 or more deep level of bill of material is created, the sum of the material should only be the sum of purchased raw components (material)...but it was summing up all first level children as material cost.   This has been fixed and will appear in patch 6.0.8.   I've created another ticket for this issue.
