### ISSUE TITLE
International customer addresses

### ISSUE THREAD

**Issue by dslocum** [blueseerERP/blueseer#78]
I'm new to Blueseer.  I am trying to import data from my very dated Quickbooks, and trying something simple to get started.  I exported my Customer list and massaged it for the number of columns, but there are several errors when trying to import into Blueseer.  

The first thing that stopped me was the 2 character STATE field.  How can I get this to work for my international customers?

Another thing is that blank non-mandatory fields complain that there must be an integer.

I haven't gone any further.

**Comment by vaughnte** [comment]
There is a two character limit to the state...which was 'originally' developed for US based state codes.   I will extend that to a higher character limit.   Can you indicate an example of state codes you are attempting to import?   ...abbreviated or otherwise.   It may be necessary to allow lengths of 'names' instead of abbreviations....depending on whether some countries have abbreviated state/provinces/etc.    The integer requirement is an old code requirement...all integer, double type fields must be '0' if blank.    I'll have to dig into this...as I thought I allowed integer blanks a few patches ago.

**Comment by vaughnte** [comment]
Extended the state field to 30 chars for countries with larger or no abbreviations for state codes.   Also added a 'remove us states' button in the customer control field.   The patch has been added to the .exe download.    The official patch will be released in the upcoming 6.3.4 patch release this week.

**Comment by vaughnte** [comment]
resolution in patch 6.3.4....and has been released...closing.

**Comment by dslocum** [comment]
Cool, thanks.  Can I simply "patch" the installation, or does it need a reinstall?  Is the DB field modified without loosing data?

**Comment by vaughnte** [comment]
A re-install is warranted in this case.   Also...note...once you have your new addresses loaded....you still have to load non-us states in Generalized Codes.   There is an import for that too.   Essentially 3 fields separated by ":".   "states","stateabbr","statename".    Once you have the non-us states loaded...there is a button to delete all us related states (if you want to) in the Customer Control menu.
